version: 2

formats:
  - epub
  - htmlzip

sphinx:
  configuration: docs/conf.py

  # Disabled due to temporary issue with Django docs
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip uninstall --yes sphinx-rtd-theme
      - pip install git+https://github.com/readthedocs/sphinx_rtd_theme.git@humitos/addons-flyout#egg=sphinx-rtd-theme